#criem um programa que peça um numero e mostre toda a sua tabuada
n1=int(input('Digite um numero a fim de saber a sua tabuada:'))
print('soma: ')
print('{} * {} ={} '.format(n1,1,n1))
print('{} * {} ={} '.format(n1,2,n1*2))
print('{} * {} ={} '.format(n1,3,n1*3))
print('{} * {} ={} '.format(n1,4,n1*4))
print('{} * {} ={} '.format(n1,5,n1*5))
print('{} * {} ={} '.format(n1,6,n1*6))
print('{} * {} ={} '.format(n1,7,n1*7))
print('{} * {} ={} '.format(n1,8,n1*8))
print('{} * {} ={} '.format(n1,9,n1*9))
print('{} * {} ={} '.format(n1,10,n1*10))
